[font]
size = 15

[font.normal]
family = "Fira Code"
style = "Medium"

[scrolling]
history = 5000
multiplier = 3

[window]
opacity = 0.95

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 5
y = 5
